[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "project"
version = "0.1.2"
authors = [{name = "Michael OConnor", email = "msoconnor2@wisc.edu"},]
description = ""

